[features]
new = []

[package]
name = "mpi-minfail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = { path = "rsmpi" }
mpi-sys = { path = "rsmpi/mpi-sys" }

[lib]
name = "mpi_minfail"
